#!/usr/bin/env bash
# Script to install a nginx server and handle a redirection
sudo apt-get update;
sudo apt-get -y install nginx;
sudo service nginx start;
echo "<marquee>Holberton School</marquee>" | sudo tee /usr/share/nginx/html/index.html;
echo "<marquee>Holberton School</marquee>" | sudo tee /var/www/html/index.nginx-debian.html;
sudo sed -i '26 i \    rewrite ^/redirect_me https://gstlabs.herokuapp.com/portfolio permanent;' /etc/nginx/sites-available/default;
sudo service nginx reload;
sudo service nginx restart;
