#!/usr/bin/env bash
# Script to install a nginx server and handle a redirection
sudo apt-get update;
sudo apt-get -y install nginx;
sudo service nginx start;
echo "<marquee>Holberton School</marquee>" | sudo tee /usr/share/nginx/html/index.html;
echo "<marquee>Holberton School</marquee>" | sudo tee /var/www/html/index.nginx-debian.html;
sudo sed -i '26 i \    rewrite ^/redirect_me https://gstlabs.herokuapp.com/portfolio permanent;location /xyz{ return 404;}error_page 404 /404.html;location = /404.html {root /usr/share/ngnix/html;internal;}' /etc/nginx/sites-available/default;
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html;
sudo service nginx reload;
sudo service nginx restart;
