#!/usr/bin/env bash
# Install the nginx server
sudo apt-get update
sudo apt-get -y install nginx
echo "
add_header X-Served-By $HOSTNAME;" |
sudo tee -a /etc/nginx/sites-available/default
sudo service nginx restart
