#!/usr/bin/env bash
# This script create a file, display indefinitely a test and show you a message
# depending of the signal getted
echo $$ >> /var/run/holbertonscript.pid
COUNTER=1
until [ $COUNTER -eq 0 ]
do
    trap ' echo "Y U no love me?!" ' INT
    trap ' echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit; ' TERM
    trap ' rm /var/run/holbertonscript.pid; exit; ' QUIT
    echo "To infinity and beyond"
    sleep 2
    let COUNTER=COUNTER+1
done
