#!/usr/bin/env bash
# This script manage the manage_my_process process.
# shellcheck disable=SC2002
PID_FILE=/var/run/my_process.pid
case $1 in
    "start" )
	echo "manage_my_process started"	
	./manage_my_process &
	echo $! > $PID_FILE
	;;
    "stop" )
	echo "manage_my_process stopped"
	cat $PID_FILE | xargs kill
	rm $PID_FILE
	;;
    "restart" )
	echo "manage_my_process restarted"
	cat $PID_FILE | xargs kill
	rm $PID_FILE
	./manage_my_process &
	echo $! > $PID_FILE
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
