#!/usr/bin/env bash                       
# This script is displays a text indefinitely
COUNTER=1
until [ $COUNTER -eq 0 ]
do
    trap ' echo "I am invincible!!!" ' TERM
    echo "To infinity and beyond"
    sleep 2
    let COUNTER=COUNTER+1
done
