#!/usr/bin/env bash
x=1
while [$x -le 100]
do
    if ((x % 3 + x % 5 == 0))
    then
	echo "FizzBuzz"
    elif ((x % 5 == 0))
    then
	echo "Buzz"
    elif ((x % 3 == 0))
    then
	echo "Fizz"
    else
	echo $x
    fi
    ((x++))
done
