#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
COUNTER=1
while [ $COUNTER -le 10 ]
do
    if [ $COUNTER -eq 10 ]; then
       echo "Hi"
    fi
    echo "Holberton School"
    ((COUNTER++))
done
