#!/usr/bin/env bash
# This script is display the number from 1 to 20
COUNTER=1
while [ $COUNTER -le 20 ]
do
    case $COUNTER in
	4 )
	    echo $COUNTER
	    echo "bad luck from China"
	    ;;
	9 )
	    echo $COUNTER
	    echo "bad luck from Japan"
	    ;;
	17 )
	    echo $COUNTER
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo $COUNTER
	    ;;
    esac
    ((COUNTER++))
done
