#!/usr/bin/env bash
# Script to install a nginx server and handle a redirection
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "/# Only for*/i\\
     location /redirect_me {\n\
     rewrite \^(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4\
     permanent;\n}\n" /etc/nginx/sites-available/default
sudo service nginx restart
