#!/usr/bin/env bash
# This script change a host configuration in a Ubuntu server.
cp /etc/hosts  ~/hosts.new;
echo -e "localhost\t\t\t127.0.0.2\nfacebook.com\t\t\t8.8.8.8" >> ~/hosts.new;
cp -f ~/hosts.new /etc/hosts;
rm -f ~/hosts.new;
