#!/usr/bin/env bash
# This script change a host configuration in a Ubuntu server.
cp /etc/hosts  ~/hosts.new;
echo "hocalhost" >> ~/hosts.new;
echo "facebook.com" >> ~/hosts.new;
sed -i 's/^hocalhost*/localhost 127.0.0.2/g' ~/hosts.new;
sed -i 's/^facebook.com*/facebook.com 8.8.8.8/g' ~/hosts.new;
cp -f ~/hosts.new /etc/hosts;
rm -f ~/hosts.new;
/etc/init.d/dns-clean restart;
